// FSEvents: the O(changes) candidate source for `world fs diff` (T1.3).
//
// Measured on 27.0 (docs/CLONE_MODEL_MACOS27.md §6.2): a replay from the fork cursor over a
// 50k-file World with 800 changes delivers 799 unique file-level paths in 21 ms, with
// MustScanSubDirs, UserDropped and KernelDropped all zero. Events are only dropped when the
// consumer is blocked, so the stream here gets a thread of its own and its callback does
// nothing but copy path bytes into a buffer; all verification happens after the join.
//
// Flags (measured in this file's own probe before it was written, see the report in
// docs/TASKS.md T1.3):
//   kFSEventStreamCreateFlagFileEvents  per-file paths instead of per-directory ones. Without
//       it a change is reported as "something under this directory changed" and every diff
//       degenerates into a directory scan.
//   kFSEventStreamCreateFlagNoDefer     deliver the first batch immediately rather than after
//       the latency window. With latency 0 it changes little, but it is what §6.2 measured.
//   NOT kFSEventStreamCreateFlagIgnoreSelf. It suppresses events generated by the process that
//       owns the stream, which for a historical replay is meaningless (the events were recorded
//       long before this stream existed, by some other process). It also would not help: the
//       only writes the fork itself does happen under its temporary clone, a path that is not
//       under the watched root, and were measured not to appear. And under P10 an extra
//       candidate costs one lstat and can never produce a wrong answer, while a wrongly
//       suppressed one would be a missed change.
//   NOT kFSEventStreamCreateFlagWatchRoot. That follows a watched root that is moved while the
//       stream is live; this stream lives for a few milliseconds and replays the past.
//   NOT kFSEventStreamCreateFlagUseCFTypes. char** paths mean no CFString allocation per event.
#include "internal.h"

#include "events.h"

#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/xattr.h>
#include <time.h>

// AssertMacros.h otherwise defines check()/verify()/require() as macros over the whole file.
#define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#include <CoreServices/CoreServices.h>
#include <dispatch/dispatch.h>

namespace wfs {

namespace {

// HistoryDone alone is not the end of the story. §6.2's "the last event arrives 3-12 ms after
// the change" was measured on a stream that was ALREADY RUNNING. A diff creates its stream
// after the fact, so a change first has to reach fseventsd's on-disk journal, and that was
// measured here on 27.0 (scratch probe, isolated single changes, five rounds each):
//
//     write     99 / 592 / 395 / 105 / 287 ms
//     chmod     97 /  91 / 326 /  89 /  91 ms
//     setxattr  91 /  90 / 155 / 296 /  91 ms
//
// ~90 ms typically, ~600 ms at worst, and the same for every kind of change. A burst flushes
// promptly (the 850-change fixture is always complete), a single lone edit waits for the timer.
//
// So the stream stays live after HistoryDone until a sentinel of our own comes back. It is
// created in the STORE directory -- never in the world, which a diff must not modify -- and the
// store is watched alongside the world. Getting it back proves the stream is alive and the
// journal has moved past the moment the diff started; not getting it back within kTailUs is
// FS_EV_TIMEOUT, i.e. a full scan. With no sentinel to wait for (a store we cannot write to)
// the stand-in is kQuietUs of silence.
//
// What the sentinel does NOT buy is a proof of completeness: journal flushes are not globally
// ordered -- a sentinel written later was measured coming back before an earlier change in
// another directory -- so a lone change made in the last ~100-600 ms can still be missing.
// Waiting it out was measured and rejected: 150 ms of extra quiet-time made the 10k diff
// 0.22-0.70 s, i.e. slower than simply walking both trees. `--full` is the exact answer and it
// is cheap (0.16 s over 50 000 files); see docs/TASKS.md T1.3.
const int64_t kQuietUs = 150 * 1000;
const int64_t kTailUs = 2 * 1000 * 1000;
const int64_t kHistoryUs = 5 * 1000 * 1000;

struct Replay {
    PathBag *bag = nullptr;
    const char *root = nullptr;
    size_t rootlen = 0;
    const char *alt = nullptr; // the same path with /private prefixed or stripped
    size_t altlen = 0;
    const char *sentinel = nullptr; // "/<leaf>" of the watermark file, matched as a suffix
    size_t sentinel_len = 0;
    int saw_sentinel = 0;
    int status = FS_EV_OK;
    int done = 0;
    uint64_t seen = 0;
    dispatch_semaphore_t sem = nullptr;
};

int64_t mono_us(void) {
    struct timespec ts;
    ::clock_gettime(CLOCK_MONOTONIC, &ts);
    return (int64_t)ts.tv_sec * 1000000 + ts.tv_nsec / 1000;
}

// FSEvents hands back the path as the kernel recorded it. On Darwin /tmp, /var and /etc are
// firmlinks onto /private, and a realpath()'d root is the /private form, so accept both.
bool strip_root(const Replay &r, const char *p, const char **rel) {
    for (int i = 0; i < 2; ++i) {
        const char *base = i ? r.alt : r.root;
        size_t n = i ? r.altlen : r.rootlen;
        if (!base || !n) continue;
        if (strncmp(p, base, n) != 0) continue;
        if (p[n] == 0) { *rel = ""; return true; }
        if (p[n] == '/') {
            *rel = p + n + 1;
            return true;
        }
    }
    return false;
}

void on_events(ConstFSEventStreamRef stream, void *info, size_t n, void *paths,
               const FSEventStreamEventFlags flags[], const FSEventStreamEventId ids[]) {
    (void)stream;
    Replay *r = (Replay *)info;
    char **p = (char **)paths;
    int status = FS_EV_OK;
    int done = 0;
    int sentinel = 0;
    (void)ids;
    for (size_t i = 0; i < n; ++i) {
        FSEventStreamEventFlags f = flags[i];
        // P10: any of these means the event stream cannot account for every change, so the
        // whole diff has to fall back to the two-tree walk. Record it and stop reading.
        if (f & kFSEventStreamEventFlagMustScanSubDirs) status = FS_EV_MUST_SCAN;
        else if (f & (kFSEventStreamEventFlagUserDropped | kFSEventStreamEventFlagKernelDropped))
            status = FS_EV_DROPPED;
        else if (f & kFSEventStreamEventFlagEventIdsWrapped) status = FS_EV_WRAPPED;
        if (f & kFSEventStreamEventFlagHistoryDone) { done = 1; continue; }
        if (status != FS_EV_OK) continue;
        if (!p[i]) continue;
        if (r->sentinel) {
            size_t n2 = strlen(p[i]);
            if (n2 >= r->sentinel_len && !strcmp(p[i] + n2 - r->sentinel_len, r->sentinel)) {
                sentinel = 1;
                continue;
            }
        }
        const char *rel = nullptr;
        if (!strip_root(*r, p[i], &rel)) continue; // the store, or not under this world at all
        if (!*rel) continue;                       // the world root itself (the publish rename)
        r->seen++;
        r->bag->add(rel);
    }
    if (status != FS_EV_OK) __atomic_store_n(&r->status, status, __ATOMIC_RELEASE);
    if (sentinel) __atomic_store_n(&r->saw_sentinel, 1, __ATOMIC_RELEASE);
    if (done) __atomic_store_n(&r->done, 1, __ATOMIC_RELEASE);
    // Every batch wakes the waiter: it is counting quiet time, not just waiting for the end.
    dispatch_semaphore_signal(r->sem);
}

// Is the cursor still inside the volume's event journal? A cursor older than the journal is
// the dangerous case: FSEvents then delivers nothing at all and never sends HistoryDone
// (measured on 27.0), which would look exactly like "no changes".
//
// FSEventsGetLastEventIdForDeviceBeforeTime is typed CFAbsoluteTime but on 27.0 it reads its
// argument as unix seconds: passing a real CFAbsoluteTime returns 0 for every time, passing a
// unix second returns a plausible id and 0 once the time predates the journal (measured: this
// machine's data volume keeps roughly 18-24 h). We pass unix seconds and treat 0 as "the
// journal no longer reaches back that far" -> full scan.
int cursor_usable(uint64_t dev, uint64_t since, int64_t since_time) {
    CFUUIDRef u = FSEventsCopyUUIDForDevice((dev_t)dev);
    if (!u) return FS_EV_STALE; // no event journal on this volume at all
    CFRelease(u);
    uint64_t now = FSEventsGetCurrentEventId();
    if (now == 0) return FS_EV_UNSUPPORTED;
    if (since > now) return FS_EV_WRAPPED; // the counter was reset behind our back
    if (since_time > 0) {
        FSEventStreamEventId last =
            FSEventsGetLastEventIdForDeviceBeforeTime((dev_t)dev, (CFAbsoluteTime)(since_time - 2));
        if (last == 0 || last == kFSEventStreamEventIdSinceNow) return FS_EV_STALE;
        // Ids are global and monotonic in time, so the last id from before the fork cannot be
        // newer than the id taken at the fork unless the journal was rebuilt.
        if (last > since) return FS_EV_STALE;
    }
    return FS_EV_OK;
}

} // namespace

int fs_events_replay(const char *root, uint64_t since, uint64_t dev, int64_t since_time,
                     const char *sentinel_dir, PathBag &out) {
    if (!root || !*root || since == 0) return FS_EV_UNSUPPORTED;
    if (int rc = cursor_usable(dev, since, since_time)) return rc;

    Replay r;
    r.bag = &out;
    r.root = root;
    r.rootlen = strlen(root);
    String alt;
    static const char kPrivate[] = "/private";
    const size_t kPrivateLen = sizeof kPrivate - 1;
    if (!strncmp(root, kPrivate, kPrivateLen) && root[kPrivateLen] == '/') {
        alt.assign(root + kPrivateLen);
    } else {
        alt.assign(kPrivate);
        alt.append(root);
    }
    r.alt = alt.c_str();
    r.altlen = alt.size();

    // The watermark. It has to exist before the stream does, so that it is either already in
    // the history or arrives right behind it.
    String sentinel_path, sentinel_leaf;
    if (sentinel_dir && *sentinel_dir) {
        char leaf[64];
        ::snprintf(leaf, sizeof leaf, "/.wfs-diff-%d", (int)::getpid());
        sentinel_leaf.assign(leaf);
        sentinel_path.assign(sentinel_dir);
        sentinel_path.append(leaf);
        ::unlink(sentinel_path.c_str());
        int fd = ::open(sentinel_path.c_str(), O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0600);
        if (fd >= 0) {
            ssize_t w = ::write(fd, "w", 1);
            (void)w;
            ::close(fd);
            r.sentinel = sentinel_leaf.c_str();
            r.sentinel_len = sentinel_leaf.size();
        } else {
            sentinel_path.assign("");
        }
    }

    CFStringRef cfp = CFStringCreateWithCString(nullptr, root, kCFStringEncodingUTF8);
    if (!cfp) return FS_EV_UNSUPPORTED;
    CFStringRef cfs = r.sentinel ? CFStringCreateWithCString(nullptr, sentinel_dir, kCFStringEncodingUTF8)
                                 : nullptr;
    const void *roots[2] = {cfp, cfs};
    CFArrayRef watched = CFArrayCreate(nullptr, roots, cfs ? 2 : 1, &kCFTypeArrayCallBacks);
    FSEventStreamContext ctx;
    memset(&ctx, 0, sizeof ctx);
    ctx.info = &r;
    FSEventStreamRef stream =
        FSEventStreamCreate(nullptr, on_events, &ctx, watched, (FSEventStreamEventId)since, 0.0,
                            kFSEventStreamCreateFlagFileEvents | kFSEventStreamCreateFlagNoDefer);
    if (!stream) {
        CFRelease(watched);
        CFRelease(cfp);
        if (cfs) CFRelease(cfs);
        if (sentinel_path.size()) ::unlink(sentinel_path.c_str());
        return FS_EV_UNSUPPORTED;
    }
    // A serial queue is a thread of its own: the callback above runs there and nothing else
    // ever does, so the consumer cannot be the reason an event is dropped.
    r.sem = dispatch_semaphore_create(0);
    dispatch_queue_t q = dispatch_queue_create("world.forks.fs.diff.replay", DISPATCH_QUEUE_SERIAL);
    FSEventStreamSetDispatchQueue(stream, q);
    int rc = FS_EV_OK;
    if (!FSEventStreamStart(stream)) {
        rc = FS_EV_UNSUPPORTED;
    } else {
        // Phase 1, the history. §6.2 measured 21 ms to replay 800 changes over a 50k tree; five
        // seconds is four orders of magnitude of headroom and still bounds the one case that
        // otherwise hangs forever (a cursor the journal cannot serve delivers nothing at all
        // and never sends HistoryDone).
        int64_t deadline = mono_us() + kHistoryUs;
        for (;;) {
            if (__atomic_load_n(&r.done, __ATOMIC_ACQUIRE)) break;
            if (__atomic_load_n(&r.status, __ATOMIC_ACQUIRE) != FS_EV_OK) break;
            int64_t left = deadline - mono_us();
            if (left <= 0) { rc = FS_EV_TIMEOUT; break; }
            dispatch_semaphore_wait(r.sem, dispatch_time(DISPATCH_TIME_NOW, left * 1000));
        }
        // Phase 2a, the watermark: wait for the sentinel to come back round.
        int64_t hard = mono_us() + kTailUs;
        if (rc == FS_EV_OK && r.sentinel && __atomic_load_n(&r.status, __ATOMIC_ACQUIRE) == FS_EV_OK) {
            while (!__atomic_load_n(&r.saw_sentinel, __ATOMIC_ACQUIRE)) {
                int64_t left = hard - mono_us();
                if (left <= 0) { rc = FS_EV_TIMEOUT; break; } // cannot say the replay is alive
                dispatch_semaphore_wait(r.sem, dispatch_time(DISPATCH_TIME_NOW, left * 1000));
            }
        }
        // Phase 2b, the stand-in when there is no sentinel: stop once the stream has been quiet.
        if (rc == FS_EV_OK && !r.sentinel && __atomic_load_n(&r.status, __ATOMIC_ACQUIRE) == FS_EV_OK) {
            for (;;) {
                int64_t left = hard - mono_us();
                if (left <= 0) break;
                if (left > kQuietUs) left = kQuietUs;
                if (dispatch_semaphore_wait(r.sem, dispatch_time(DISPATCH_TIME_NOW, left * 1000)) != 0)
                    break; // quiet: nothing more is arriving for this world
            }
        }
        FSEventStreamStop(stream);
    }
    FSEventStreamInvalidate(stream);
    FSEventStreamRelease(stream);
    dispatch_release(q);
    dispatch_release(r.sem);
    CFRelease(watched);
    CFRelease(cfp);
    if (cfs) CFRelease(cfs);
    if (sentinel_path.size()) ::unlink(sentinel_path.c_str());
    if (rc == FS_EV_OK && r.status != FS_EV_OK) rc = r.status;
    if (rc == FS_EV_OK && !r.done) rc = FS_EV_TIMEOUT;
    return rc;
}

} // namespace wfs
